### ISSUE TITLE
Character Selection (Which character do you want to be)

### ISSUE THREAD

**Issue by AidenSPS** [AidenSPS/Coders-Batman-RPG-Kanban#1]
Are we going to have a "point" system to signify which character we are going to be (similar to errorDist from Multiplication) Or, are we going to have it so that the user can choose which character they want to be?

**Comment by bmoreinis** [comment]
We have a point system.  That's the code you started writing yesterday and Chris and I finished today.  Check out script.js here: https://github.com/bmoreinis/RPG-BatmanCode

**Comment by bmoreinis** [comment]
If you qualify for multiple characters, then you pick which one you want to be.
